import os
import re
import base64
import markdown
from playwright.sync_api import sync_playwright

def find_walkthrough_md():
    possible_paths = [
        r"d:\OneDrive - TECHFROST\Antigravity MS Laptop\M365 Admin Bot\walkthrough.md",
        r"C:\Users\guptha1989\.gemini\antigravity-ide\brain\a1b8bd4c-7664-4efc-be7a-c25a39e5f716\walkthrough.md",
        r"C:\Users\guptha1989\.gemini\antigravity-ide\brain\bff501f3-c94e-4d72-8137-dc5772655fcb\walkthrough.md",
    ]
    for path in possible_paths:
        if os.path.exists(path):
            print(f"[+] Found walkthrough.md at: {path}")
            return path
    raise FileNotFoundError("Could not locate walkthrough.md in known paths.")

def process_callouts(md_text):
    """
    Converts GitHub-style callouts like > [!NOTE] into custom HTML blocks.
    """
    callout_types = {
        "NOTE": {"class": "alert-note", "title": "Note", "icon": "ℹ️"},
        "TIP": {"class": "alert-tip", "title": "Tip", "icon": "💡"},
        "IMPORTANT": {"class": "alert-important", "title": "Important", "icon": "📌"},
        "WARNING": {"class": "alert-warning", "title": "Warning", "icon": "⚠️"},
        "CAUTION": {"class": "alert-caution", "title": "Caution", "icon": "🚨"},
    }

    lines = md_text.split('\n')
    new_lines = []
    in_callout = False
    callout_data = None
    callout_body = []

    for line in lines:
        match = re.match(r'^>\s*\[\!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*(.*)$', line, re.IGNORECASE)
        if match:
            if in_callout:
                # Flush existing callout
                html_block = render_callout_html(callout_data, callout_body)
                new_lines.append(html_block)
                callout_body = []
            
            ctype = match.group(1).upper()
            callout_data = callout_types.get(ctype, callout_types["NOTE"])
            first_text = match.group(2).strip()
            if first_text:
                callout_body.append(first_text)
            in_callout = True
            continue

        if in_callout:
            if line.startswith('>'):
                content = re.sub(r'^>\s?', '', line)
                callout_body.append(content)
            else:
                # End of callout
                html_block = render_callout_html(callout_data, callout_body)
                new_lines.append(html_block)
                in_callout = False
                callout_body = []
                callout_data = None
                new_lines.append(line)
        else:
            new_lines.append(line)

    if in_callout:
        html_block = render_callout_html(callout_data, callout_body)
        new_lines.append(html_block)

    return '\n'.join(new_lines)

def render_callout_html(data, body_lines):
    body_text = ' '.join(body_lines).strip()
    return f'''
<div class="alert-box {data['class']}">
    <div class="alert-title">{data['icon']} <strong>{data['title']}</strong></div>
    <div class="alert-body">{body_text}</div>
</div>
'''

def convert_images_to_base64(html_content, base_dir):
    """
    Replaces img src attributes pointing to local files with Base64 data URIs.
    Wraps img tags in <figure> and <figcaption>.
    """
    def replace_img(match):
        alt = match.group(1) or ""
        src = match.group(2) or ""

        # Clean file protocol if present
        clean_path = src.replace("file:///", "").replace("file://", "")
        clean_path = clean_path.replace("/", "\\") if os.name == 'nt' else clean_path

        if not os.path.isabs(clean_path):
            clean_path = os.path.join(base_dir, clean_path)

        data_uri = src
        if os.path.exists(clean_path):
            try:
                ext = os.path.splitext(clean_path)[1].lower().replace('.', '')
                if ext == 'jpg': ext = 'jpeg'
                elif ext == 'svg': ext = 'svg+xml'
                
                with open(clean_path, 'rb') as img_f:
                    encoded = base64.b64encode(img_f.read()).decode('utf-8')
                    data_uri = f"data:image/{ext};base64,{encoded}"
                print(f"[+] Embedded image: {os.path.basename(clean_path)}")
            except Exception as e:
                print(f"[!] Warning: Failed to embed image {clean_path}: {e}")
        else:
            print(f"[!] Warning: Image file not found: {clean_path}")

        caption_html = f"<figcaption>{alt}</figcaption>" if alt else ""
        return f'<figure><img src="{data_uri}" alt="{alt}" />{caption_html}</figure>'

    # Regex matching <img alt="..." src="..." /> generated by markdown parser
    img_pattern = re.compile(r'<img\s+alt="([^"]*)"\s+src="([^"]+)"\s*/?>', re.IGNORECASE)
    return img_pattern.sub(replace_img, html_content)

def convert_mermaid_blocks(html_content):
    """
    Converts <pre><code class="language-mermaid">...</code></pre> into <div class="mermaid">...</div>
    """
    pattern = re.compile(r'<pre><code class="language-mermaid">(.*?)</code></pre>', re.DOTALL)
    def repl(m):
        code = m.group(1).replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&")
        return f'<div class="mermaid-container"><div class="mermaid">\n{code}\n</div></div>'
    return pattern.sub(repl, html_content)

def generate_full_html(body_html):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Microsoft 365 Administration & AI Governance Platform Walkthrough</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        @page {{
            size: A4;
            margin: 22mm 18mm 22mm 18mm;
        }}

        body {{
            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, Helvetica, Arial, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            font-size: 13.5px;
            background-color: #ffffff;
        }}

        /* Document Banner Header */
        .doc-header {{
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            color: #ffffff;
            padding: 28px 32px;
            border-radius: 12px;
            margin-bottom: 28px;
            border-left: 6px solid #0078d4;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
        }}

        .doc-header h1 {{
            font-size: 26px;
            font-weight: 700;
            margin: 0 0 6px 0;
            color: #ffffff;
            border-bottom: none;
            padding-bottom: 0;
            letter-spacing: -0.3px;
        }}

        .doc-header h2 {{
            font-size: 15px;
            font-weight: 400;
            color: #94a3b8;
            margin: 0 0 18px 0;
            border-bottom: none;
            padding-bottom: 0;
        }}

        .header-badges {{
            display: flex;
            gap: 12px;
            flex-wrap: wrap;
        }}

        .badge {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-size: 11px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        .badge-status {{ background-color: #0284c7; color: #ffffff; }}
        .badge-version {{ background-color: #334155; color: #e2e8f0; border: 1px solid #475569; }}
        .badge-date {{ background-color: #334155; color: #e2e8f0; border: 1px solid #475569; }}

        /* Headings */
        h1, h2, h3, h4 {{
            color: #0f172a;
            font-weight: 600;
            break-after: avoid;
        }}

        h1 {{
            font-size: 22px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 8px;
            margin-top: 32px;
            margin-bottom: 16px;
            color: #0078d4;
        }}

        h2 {{
            font-size: 17px;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 6px;
            margin-top: 24px;
            margin-bottom: 12px;
            color: #0f172a;
        }}

        h3 {{
            font-size: 14.5px;
            margin-top: 18px;
            margin-bottom: 8px;
            color: #334155;
        }}

        hr {{
            border: none;
            border-top: 1px solid #e2e8f0;
            margin: 24px 0;
        }}

        /* Lists */
        ul, ol {{
            padding-left: 22px;
            margin-top: 6px;
            margin-bottom: 12px;
        }}

        li {{
            margin-bottom: 4px;
        }}

        /* Tables */
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 18px 0;
            font-size: 12.5px;
            break-inside: avoid;
            box-shadow: 0 1px 3px rgba(0,0,0,0.05);
            border-radius: 6px;
            overflow: hidden;
            border: 1px solid #cbd5e1;
        }}

        th {{
            background-color: #1e293b;
            color: #ffffff;
            font-weight: 600;
            text-align: left;
            padding: 10px 14px;
            border: 1px solid #334155;
        }}

        td {{
            padding: 9px 14px;
            border: 1px solid #e2e8f0;
            color: #334155;
            vertical-align: top;
        }}

        tr:nth-child(even) {{
            background-color: #f8fafc;
        }}

        /* Code & Preformatted */
        code {{
            font-family: 'Cascadia Code', 'Consolas', 'Courier New', monospace;
            background-color: #f1f5f9;
            color: #0f172a;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 12px;
            border: 1px solid #e2e8f0;
        }}

        pre {{
            background-color: #0f172a;
            color: #f8fafc;
            padding: 14px 18px;
            border-radius: 8px;
            font-family: 'Cascadia Code', 'Consolas', monospace;
            font-size: 12px;
            line-height: 1.5;
            overflow-x: auto;
            margin: 16px 0;
            break-inside: avoid;
            border: 1px solid #1e293b;
        }}

        pre code {{
            background-color: transparent;
            color: inherit;
            padding: 0;
            border: none;
            font-size: inherit;
        }}

        /* Images & Figures */
        figure {{
            margin: 22px 0;
            text-align: center;
            break-inside: avoid;
        }}

        img {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            border: 1px solid #cbd5e1;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
        }}

        figcaption {{
            margin-top: 8px;
            font-size: 11.5px;
            color: #64748b;
            font-style: italic;
        }}

        /* Alert Boxes */
        .alert-box {{
            padding: 14px 18px;
            border-radius: 8px;
            margin: 16px 0;
            break-inside: avoid;
            border-left: 5px solid;
            font-size: 13px;
        }}

        .alert-title {{
            font-size: 13.5px;
            margin-bottom: 4px;
            display: flex;
            align-items: center;
            gap: 6px;
        }}

        .alert-body {{
            line-height: 1.5;
        }}

        .alert-note {{ background-color: #eff6ff; border-left-color: #3b82f6; color: #1e40af; }}
        .alert-tip {{ background-color: #ecfdf5; border-left-color: #10b981; color: #065f46; }}
        .alert-important {{ background-color: #f5f3ff; border-left-color: #8b5cf6; color: #5b21b6; }}
        .alert-warning {{ background-color: #fffbe6; border-left-color: #f59e0b; color: #92400e; }}
        .alert-caution {{ background-color: #fef2f2; border-left-color: #ef4444; color: #991b1b; }}

        /* Mermaid Container */
        .mermaid-container {{
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 20px 0;
            padding: 16px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            break-inside: avoid;
        }}

        .mermaid {{
            width: 100%;
            max-width: 750px;
            text-align: center;
        }}
    </style>
</head>
<body>
    <div class="doc-header">
        <h1>Microsoft 365 Administration & AI Governance Platform</h1>
        <h2>Enterprise Solution Overview, Architectural Dossier & Feature Walkthrough</h2>
        <div class="header-badges">
            <span class="badge badge-status">Executive Approved</span>
            <span class="badge badge-version">v2.4 Production</span>
            <span class="badge badge-date">September 2026</span>
        </div>
    </div>

    {body_html}

    <script>
        document.addEventListener("DOMContentLoaded", function() {{
            mermaid.initialize({{
                startOnLoad: true,
                theme: 'default',
                flowchart: {{ useMaxWidth: true, htmlLabels: true, curve: 'basis' }},
                securityLevel: 'loose'
            }});
        }});
    </script>
</body>
</html>
"""

def main():
    md_path = find_walkthrough_md()
    base_dir = os.path.dirname(md_path)

    with open(md_path, 'r', encoding='utf-8') as f:
        md_text = f.read()

    print("[+] Processing callout alerts...")
    md_text_processed = process_callouts(md_text)

    print("[+] Converting Markdown to HTML...")
    md_engine = markdown.Markdown(extensions=['tables', 'fenced_code', 'attr_list', 'toc'])
    raw_html = md_engine.convert(md_text_processed)

    print("[+] Converting Mermaid blocks...")
    html_mermaid = convert_mermaid_blocks(raw_html)

    print("[+] Embedding local images as Base64...")
    html_with_images = convert_images_to_base64(html_mermaid, base_dir)

    print("[+] Generating styled full HTML page...")
    final_html = generate_full_html(html_with_images)

    temp_html_path = os.path.join(base_dir, "temp_walkthrough.html")
    with open(temp_html_path, 'w', encoding='utf-8') as f:
        f.write(final_html)
    print(f"[+] Saved temporary HTML to: {temp_html_path}")

    # Output paths
    output_pdf_paths = [
        r"d:\OneDrive - TECHFROST\Antigravity MS Laptop\M365 Admin Bot\walkthrough.pdf",
        r"d:\OneDrive - TECHFROST\Antigravity MS Laptop\M365 Admin Bot\Microsoft_365_Admin_and_AI_Governance_Walkthrough.pdf",
        r"C:\Users\guptha1989\.gemini\antigravity-ide\brain\bff501f3-c94e-4d72-8137-dc5772655fcb\walkthrough.pdf"
    ]

    print("[+] Launching Playwright Chromium to render PDF...")
    with sync_playwright() as p:
        browser = None
        # Try standard launch, fallback to installed chrome executable or msedge/chrome channels
        try:
            browser = p.chromium.launch(headless=True)
        except Exception as e:
            print(f"[!] Standard chromium launch failed: {e}. Trying executable_path fallback...")
            existing_chrome = r"C:\Users\guptha1989\AppData\Local\ms-playwright\chromium-1243\chrome-win64\chrome.exe"
            if os.path.exists(existing_chrome):
                try:
                    browser = p.chromium.launch(executable_path=existing_chrome, headless=True)
                except Exception as e2:
                    print(f"[!] Executable path launch failed: {e2}")

            if not browser:
                for channel in ["msedge", "chrome"]:
                    try:
                        print(f"[+] Trying browser channel '{channel}'...")
                        browser = p.chromium.launch(channel=channel, headless=True)
                        break
                    except Exception as e3:
                        print(f"[!] Channel '{channel}' failed: {e3}")

        if not browser:
            raise RuntimeError("Failed to launch any Chromium/Browser instance.")

        page = browser.new_page()

        # Load local HTML file
        page.goto(f"file:///{temp_html_path.replace('\\', '/')}", wait_until="networkidle")

        # Wait for mermaid SVG rendering
        print("[+] Waiting for Mermaid diagrams to finish rendering...")
        try:
            page.wait_for_selector(".mermaid svg", timeout=12000)
            print("[+] Mermaid diagrams rendered successfully!")
        except Exception as e:
            print(f"[!] Note on Mermaid rendering wait: {e}")

        header_template = """
        <div style="font-size: 8px; font-family: 'Segoe UI', sans-serif; color: #64748b; width: 100%; display: flex; justify-content: space-between; padding: 0 18mm; box-sizing: border-box;">
            <span>Microsoft 365 Administration & AI Governance Platform</span>
            <span>Executive Feature Walkthrough</span>
        </div>
        """

        footer_template = """
        <div style="font-size: 8px; font-family: 'Segoe UI', sans-serif; color: #64748b; width: 100%; display: flex; justify-content: space-between; padding: 0 18mm; box-sizing: border-box;">
            <span>CONFIDENTIAL & PROPRIETARY — IT & AI GOVERNANCE TEAM</span>
            <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
        </div>
        """

        for pdf_path in output_pdf_paths:
            os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
            page.pdf(
                path=pdf_path,
                format="A4",
                print_background=True,
                display_header_footer=True,
                header_template=header_template,
                footer_template=footer_template,
                margin={
                    "top": "22mm",
                    "bottom": "22mm",
                    "left": "18mm",
                    "right": "18mm"
                }
            )
            print(f"[SUCCESS] Exported PDF to: {pdf_path}")

        browser.close()

    # Clean up temp HTML file
    if os.path.exists(temp_html_path):
        os.remove(temp_html_path)

if __name__ == "__main__":
    main()
